#!/usr/bin/env bash
# Bash script that configures the Ubuntu server
# Install nginx on the server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
